# Generated by Django 4.2.2 on 2023-06-09 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flotilla', '0002_area_alter_modelo_marca_alter_vehiculo_notas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SerieVales',
            fields=[
                ('Serie', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FolioInicial', models.SmallIntegerField()),
                ('FolioFinal', models.SmallIntegerField()),
                ('FolioActual', models.SmallIntegerField()),
                ('FechaExpedicion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Suministro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recibe', models.CharField(max_length=200)),
                ('Fecha', models.DateField()),
                ('Litros', models.SmallIntegerField()),
                ('Conductor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotilla.conductor')),
                ('Serie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='combustible.serievales')),
                ('Vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotilla.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Folio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero', models.IntegerField()),
                ('Litros', models.SmallIntegerField()),
                ('Estatus', models.SmallIntegerField(choices=[(1, 'Resguardo'), (2, 'Entregado'), (3, 'Aplicado'), (4, 'Cancelado')], default=1)),
                ('Suministro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='combustible.suministro')),
            ],
        ),
    ]
