# Generated by Django 4.2.2 on 2023-06-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Clave', models.CharField(max_length=10)),
                ('Marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotilla.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anio', models.SmallIntegerField(default=0)),
                ('Color', models.CharField(max_length=20)),
                ('Placas', models.CharField(max_length=20)),
                ('Serie', models.CharField(max_length=50)),
                ('Alias', models.CharField(max_length=50)),
                ('Notas', models.TextField()),
                ('Modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flotilla.modelo')),
            ],
        ),
    ]
